name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flask=2.0.2
  - pytorch=1.11.0
  - transformers=4.44.1
  - pillow=9.3.0
  - werkzeug=2.0.3
  - numpy<2
  - cmake
  - pip
  - pip:
    - huggingface-hub>=0.23.2
    - elasticsearch==8.6.2
